### ISSUE TITLE
Latest build missing enablerapi.exe

### ISSUE THREAD

**Issue by still-dreaming-1** [nlitsme/legacy-itslib-library#1]
Can you create a release with the binary files? I am having to support an old project that runs on a Windows CE device. We are getting away from supporting it as much as possible, but we still need to use it for certain things.

I tried using the latest download (itsutilsbin-20111201.zip) available at https://itsme.home.xs4all.nl/projects/xda/tools.html
However, when I use certain tools, such as pkill.exe and psynctime.exe, I get the error:

> Source/host file does not exist 'C:\hacking\itsutilsbin-20111201\enablerapi.exe'

I can't find "enablerapi.exe" anywhere. Is it supposed to be in the zip download?

**Comment by still-dreaming-1** [comment]
I just realized this repo is for a related library, but maybe not exactly for the itsutils themsevles? Anyway, I discovered if I manually copy itsutils.dll to the Windows directory on the device, I no longer get those error messages. However, for "pkill.exe" it just hangs until I `Ctrl+C` it.

**Comment by nlitsme** [comment]
you are right, this repo might be named a bit confusingly.

I think I will make a 'itsutils' repo with the old windows ce tools.

I will just use the old releases. since I don't have a windows system anymore capable of building the old code.
